import { StyleSheet } from "react-native";
import colors from "../../assets/colors/colors";
export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.pink,
        paddingTop:50
    },
    text:{
        color:'white',
        fontSize:16,
        margin:10
    },
    photo_container:{
        backgroundColor:'white',
        margin:10,
        borderRadius:8,
        elevation:10,
        marginTop:50,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingRight:10
    },
    button:{
        backgroundColor:'#A6055E',
        marginTop:50,
        margin:10,
        borderRadius:8,
        elevation:10,
        padding:10,
        alignItems:'center',
        justifyContent:'center'
    },
    button_text:{
        color:'white',
        fontSize:16,
        fontWeight:'bold'
    }
})